[build]
  publish = "frontend/public"
  command = "echo 'Using static files from frontend/public'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://ai-proposal-backend.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/advanced-app.html"
  status = 200

[headers]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"